name: freezeAll
version: 1.1
api: 3.15.1
main: Freeze\Main
author: Pralexkid

commands:
  freezeall:
    description: Freeze tout les joueurs du serveurs !
    permission: freeze.all
  freeze:
    description: Freeze un joueur spécifique !
    permission: freeze.single
